### ISSUE TITLE
Encountering an exception when attempting to connect to ST8300M

### ISSUE THREAD

**Issue by alex-nicholas** [cedric-r/ASCOM.HomeMade.SBIGCamera#10]
Just wondering if I can get some assistance with an issue I'm having.
On my micro-pc, I get the following exception when I attempt to connect to my SBIG ST8300M through NINA.

```
ERROR|AscomDevice.cs|Connect|241
ASCOM.DriverException: Unable to load DLL 'HomeMade.SBIGUDrv.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SbigSharp.SBIGDLL.SBIGUnivDrvCommand(PAR_COMMAND command, IntPtr Params, IntPtr pResults)
   at SbigSharp.SBIG.SBIGUnivDrvCommand(PAR_COMMAND command, IntPtr Params, IntPtr pResults)
   at SbigSharp.SBIG._UnivDrvCommand(PAR_COMMAND command, IntPtr Params, IntPtr pResults)
   at SbigSharp.SBIG.UnivDrvCommand(PAR_COMMAND command)
   at ASCOM.HomeMade.SBIGCommon.SBIGHandler.Connect(String ipAddress)
   at ASCOM.HomeMade.SBIGHub.SharedResources.Connect(String ipAddress)
   at ASCOM.HomeMade.SBIGClient.SBIGClient.Connect(String ipAddress)
   at ASCOM.HomeMade.SBIGCamera.SBIGCamera.set_Connected(Boolean value)
 ---> System.Exception: Unable to load DLL 'HomeMade.SBIGUDrv.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SbigSharp.SBIGDLL.SBIGUnivDrvCommand(PAR_COMMAND command, IntPtr Params, IntPtr pResults)
   at SbigSharp.SBIG.SBIGUnivDrvCommand(PAR_COMMAND command, IntPtr Params, IntPtr pResults)
   at SbigSharp.SBIG._UnivDrvCommand(PAR_COMMAND command, IntPtr Params, IntPtr pResults)
   at SbigSharp.SBIG.UnivDrvCommand(PAR_COMMAND command)
   at ASCOM.HomeMade.SBIGCommon.SBIGHandler.Connect(String ipAddress)
   at ASCOM.HomeMade.SBIGHub.SharedResources.Connect(String ipAddress)
   at ASCOM.HomeMade.SBIGClient.SBIGClient.Connect(String ipAddress)
   at ASCOM.HomeMade.SBIGCamera.SBIGCamera.set_Connected(Boolean value)

   --- End of inner exception stack trace ---
   at ASCOM.DriverAccess.MemberFactory.CheckDotNetExceptions(String memberName, Exception e) in C:\ASCOM Build\Export\ASCOM.DriverAccess\MemberFactory.cs:line 637
   at ASCOM.DriverAccess.MemberFactory.SetTargetInvocationExceptionHandler(String memberName, Exception e) in C:\ASCOM Build\Export\ASCOM.DriverAccess\MemberFactory.cs:line 654
   at ASCOM.DriverAccess.MemberFactory.CallMember(Int32 memberCode, String memberName, Type[] parameterTypes, Object[] parms) in C:\ASCOM Build\Export\ASCOM.DriverAccess\MemberFactory.cs:line 372
   at ASCOM.DriverAccess.AscomDriver.set_Connected(Boolean value) in C:\ASCOM Build\Export\ASCOM.DriverAccess\AscomDriver.cs:line 161
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at NINA.Equipment.Equipment.AscomDevice`3.set_Connected(Boolean value) in C:\Projects\nina\NINA.Equipment\Equipment\AscomDevice.cs:line 143
   at NINA.Equipment.Equipment.AscomDevice`3.<<Connect>b__45_0>d.MoveNext() in C:\Projects\nina\NINA.Equipment\Equipment\AscomDevice.cs:line 235
```

The same version of the driver and NINA are running on my main laptop, but I'm trying to migrate to the new MicroPC and can't seem to get past this issue.

I have reinstalled the ASCOM, the SBIG native drivers, the HomeMade.SBIGCamera driver. 

The MicroPC NINA instance is connecting to my mount via ASCOM without an issue, and to PHD2 via ASCOM, so I don't think that that the ASCOM platform or NINA are the issue here - I'd say something has gone sideways on the installation of the SBIG ASCOM driver. 

Would love to hear your thoughts.

Also - Thank you so much for providing an ASCOM driver for the SBIG cameras... I'm a .NET dev, and was planning on having a crack at it until I found yours! On my main laptop - its flawless!

**Comment by cedric-r** [comment]
Hi there.

The error isn't clear. But it could be a problem with some installations of windows I fixed recently when I encountered it setting up a new machine too. Did you try the very least version? It installs a syndromes missing DLL.

If it's not that, it could be that the SBIG system driver isn't installed properly or isn't reachable (no idea why that would be I've never seen that error).

Try installing the latest version first to see if it fixes the issue.

Thanks.

**Comment by alex-nicholas** [comment]
I have v 1.3.1.1 installed, and double checked the SBIG driver checker x64 - everything seemed in order.
However, I noticed that the driver checker was unable to detect my cameras firmware version - with the same error, that it couldn't load SBIGUdrv.dll. 

I removed and re-installed the SBIG drivers with the driver checker, this did not solve the problem.

I found a thread on Cloudy Nights forum where a user had posted a link to an updated SBIGUdrv.dll that SBIG silently released, and that the driver checker does not download automatically. 

Downloading this dll and replacing the original (in C:\Windows\System32\Drivers\SBIG), not only allowed me to check the firmware on my camera, but I could now connect the camera to NINA via your ASCOM interface.

More surprisingly than that though, my ST8300M now shows up in NINA using its native driver. 

I'm going to continue using the ASCOM driver as I've been using it for a few weeks now on my laptop and its been perfect, and I don't want to introduce any potential differences as I'm mid way through a very long exposure project.

The SBIG 64 bit driver can be found on this page:
https://diffractionlimited.com/legacy-product-support/

If you scroll down, you'll see the Driver Checker, which you do still need to install and run, but below that there are two links:
[SBIGUDrv 5.0.2.0 64-bit DLL](https://cdn.diffractionlimited.com/downloads/sbigudrv-5.0.2.0-vc141-x64.zip) / [SBIGUDrv 4.9.9.8 64-bit DLL](https://cdn.diffractionlimited.com/downloads/SBIGUDrv.v4.9.9.8-vc141.x64.zip).

I tried both, and both allowed me to connect via ASCOM and connect to NINA using SBIGs native driver.

Theres reference to this in your README.md, however there are no links provided.
If you'd like I can add a small section to the README and include the links then submit a PR, otherwise, you may want to add those links in.

Thanks again for your driver! I'm very happy someone took the time to make these as the SBIG cameras, though aging now (My ST8300M is 12 years old, and my ST10XME has to be 17 or 18 years old now), are still phenominal imaging systems and shouldn't be at end of life.

Thanks
Alex.

**Comment by cedric-r** [comment]
Hi Alex,

Thanks for that. It's good you figured it out. It must be that some versions of windows (windows 11 maybe?) have changed something and the previous drivers no longer work. I don't have that version since the drivers work on all the machines I installed them on. I had no change of figuring it out.

I distribute that DLL with the driver, but it's a previous version. I'll get the new one and add it to the ASCOM driver so they're available.

Thanks,
